### ISSUE TITLE
Setting the NSTextAttachment bounds is useless

### ISSUE THREAD

**Issue by cailei1** [shinjukunian/DocX#10]
let image1Attachment = NSTextAttachment()
            image1Attachment.bounds = CGRect(x: 0, y: 0, width: 40 , height: 300)
            image1Attachment.image = image
            // wrap the attachment in its own attributed string so we can append it
            let image1String = NSAttributedString(attachment: image1Attachment)

            // add the NSTextAttachment wrapper to our full string, then add some more text.
            fullString.append(image1String)

          
            I have set the image display bounds , but generate docx display very big and beyond the words width then only dispaly 
            half of image

**Comment by shinjukunian** [comment]
Hi,
thank you for reporting this. This is indeed an oversight - I have ignored the bounds property of `NSTextAttachement`. This is now fixed in #11  - feel free to have a look. I will merge this into the `master` branch later this week.  Please let me know if this  solves the issue or if you have any further suggestions.

Cheers from Tokyo

Morten

**Comment by cailei1** [comment]
HI,
thank you for reply me. i have tested this bug,I am glad it has been resolved.I am very grateful to you, I searched the whole network but couldn't find the plan that convert to word,thank you very much again.
