### ISSUE TITLE
I can't get the examples to compile as I get this error....

### ISSUE THREAD

**Issue by chrisriner** [shinjukunian/DocX#2]
/Users/christopherriner/Downloads/DocX-master/DocX/NSAttributedString+DocX.swift:26:35: Type 'Bundle' has no member 'module'

**Comment by shinjukunian** [comment]
The lates commit should have resolved this - sorry for not getting to this issue earlier.

**Comment by chrisriner** [comment]
Thanks very much.  I tried it and it works now.  I was wondering if I could get your opinion on what I am trying to do.  I was looking for a way to generate a word doc in code.  I have to let a user enter lots and lots of data and then I store it in core data and then they want to tap a button and then my app should take all of that data plus some images and generate a word doc that they can then export from the app to one drive and edit it more on a laptop.  I am trying to see if this library would help me in creating a word doc for them in code using the data they have entered.  They do not need to edit anything directly in the app just enter the data and then the app generates word doc.  The word doc again would have text and pictures and tables and will be very large. Do you think you library would be helpful in doing that?

**Comment by shinjukunian** [comment]
Hi @chrisriner,

I'm glad everything is working now - since migrating to SPM the framework targets haven't been used in my projects.
DocX is designed around NSAttributedString and is this limited by the functionality of this API - hence no tables, pagination etc. Images are in principle supported by NSAttributedString (through NSTextAttachement) but I have not implemented this since images (and their placement etc.) are pretty clunky in both TextKit and .docx

Cheers

Morten
