### ISSUE TITLE
Question for use of code...

### ISSUE THREAD

**Issue by chrisriner** [shinjukunian/DocX#3]
Thanks very much for the help closing my issue. I tried it and it works now. I was wondering if I could get your opinion on what I am trying to do. I was looking for a way to generate a word doc in code. I have to let a user enter lots and lots of data and then I store it in core data and then they want to tap a button and then my app should take all of that data plus some images and generate a word doc that they can then export from the app to one drive and edit it more on a laptop. I am trying to see if this library would help me in creating a word doc for them in code using the data they have entered. They do not need to edit anything directly in the app just enter the data and then the app generates word doc. The word doc again would have text and pictures and tables and will be very large. Do you think you library would be helpful in doing that?

**Comment by shinjukunian** [comment]
Hi @chrisriner 
DocX is designed around NSAttributedString and is thus limited by the functionality of this API - hence no tables, pagination etc. Images are in principle supported by NSAttributedString (through NSTextAttachement) but I have not implemented this yet since images (and their placement etc.) are pretty clunky in both TextKit and .docx.

**Comment by shinjukunian** [comment]
@chrisriner 
just for your information, the latest version (0.8.1) df144b983dd8d03ebf919108c9ccd91b3333e131 supports image export using `NSTextAttachment`
